"""
Configuración de los comercializadores disponibles y sus instrucciones específicas.
"""

COMERCIALIZADORES = {
    "ENERTOTAL": {
        "name": "Enertotal",
        "instrucciones_file": "config/instrucciones/enertotal.txt",
        "mercado_mapping": {
            "MCDO ANTIOQUIA UNIF": "ANTIOQUIA",
            "MERCADO CARIBE SOL": "CARIBE SOL",
            "MERCADO CARIBE MAR": "CARIBE MAR",
            "MERCADO BOYACA": "BOYACA",
            "MERCADO CALI": "CALI",
            "MERCADO CALDAS": "CALDAS",
            "MERCADO CARTAGO": "CARTAGO",
            "CAQUETA": "CAQUETA",
            "MERCADO CAUCA": "CAUCA",
            "CESAR": "CESAR",
            "CHOCO": "CHOCO",
            "CORDOBA": "CORDOBA",
            "MERCADO BOGOTA": "BOGOTA",
            "MERCADO HUILA": "HUILA",
            "LA GUAJIRA": "LA GUAJIRA",
            "MAGDALENA": "MAGDALENA",
            "MERCADO META": "META",
            "MERCADO NARIÑO": "NARIÑO",
            "NORTE DE SANTANDER": "NORTE DE SANTANDER",
            "MERCADO QUINDIO": "QUINDIO",
            "MERCADO PEREIRA": "PEREIRA",
            "MERCADO SANTANDER": "SANTANDER",
            "MERCADO TOLIMA": "TOLIMA",
            "MERCADO VALLE": "VALLE",
            "MERCADO CETSA": "TULUA"
        },
        "tension_mapping": {
   "Nivel 1.1": "1 OR",
   "N 1.2* - 50%": "1 COMP",
   "N 1.2-1.3": "1 US",
   "Nivel 2": "2",
    "Nivel 3": "3"
        }
    },
    "ENELX": {
        "name": "ENELX",
        "instrucciones_file": "config/instrucciones/enelx.txt",
        "mercado_mapping": {
            "BOGOTÁ Y CUNDINAMARCA": "BOGOTA",
            "ANTIOQUIA": "ANTIOQUIA",
            "BOLIVAR, CESAR, CÓRDOBA, SUCRE": "CARIBE MAR",
            "ATLÁNTICO, MAGDALENA, GUAJIRA": "CARIBE SOL",
            "CALI": "CALI",
            "CASANARE": "CASANARE",
            "CALDAS": "CALDAS",
            "SANTANDER": "SANTANDER",
            "NORTE DE SANTANDER": "NORTE SANTANDER",
            "META": "META",
            "QUINDIO": "QUINDIO",
            "NARIÑO": "NARIÑO",
            "RISARALDA": "RISARALDA",
            "HUILA": "HUILA",
            "VALLE DEL CAUCA": "VALLE",
            "TULUÁ": "TULUA",
            "TOLIMA": "TOLIMA",
            "BOYACÁ": "BOYACA",
            "SANTANDER RUITOQUE": "RUITOQUE"
        },
        "tension_mapping": {
            "1 OR": "1 OR",
            "1 COMP": "1 COMP",
            "1 US": "1 US",
            "2": "2",
            "3": "3",
            "4": "4"
        }
    },
    "ENERBIT": {
        "name": "Enerbit",
        "instrucciones_file": "config/instrucciones/enerbit.txt",
        "mercado_mapping": {
            "ANTIOQUIA": "ANTIOQUIA",
            "ATLANTICO": "ATLANTICO",
            "AFINIA": "CARIBE MAR",
            "BOLIVAR": "BOLIVAR",
            "BOYACA": "BOYACA",
            "CHEC": "CALDAS",
            "CALI, YUMBO Y PUERTO TEJADA": "CALI",
            "CARTAGO": "CARTAGO",
            "CAQUETA": "CAQUETA",
            "CAUCA": "CAUCA",
            "CESAR": "CESAR",
            "CHOCO": "CHOCO",
            "CORDOBA": "CORDOBA",
            "HUILA": "HUILA",
            "CUNDINAMARCA": "CUNDINAMARCA",
            "HUILA": "HUILA",
            "LA GUAJIRA": "LA GUAJIRA",
            "MAGDALENA": "MAGDALENA",
            "META": "META",
            "NARIÑO": "NARIÑO",
            "NORTE DE SANTANDER": "NORTE DE SANTANDER",
            "QUINDIO": "QUINDIO",
            "PEREIRA": "PEREIRA",
            "SANTANDER": "SANTANDER",
            "TOLIMA": "TOLIMA",
            "VALLE": "VALLE",
            "TULUÁ": "TULUA"
        },
        "tension_mapping": {
            "CU1 Prop, OR": "1 OR",
            "CU12 Prop, Mixta": "1 COMP",
            "CU1 Prop, Cliente": "1 US",
            "CU2": "2",
            "CU3": "3"
        }
    },
    "VATIA": {
        "name": "Vatia",
        "instrucciones_file": "config/instrucciones/vatia.txt",
        "mercado_mapping": {
            "EPSA": "VALLE",
            "PUTUMAYO": "PUTUMAYO",
            "EDEQ": "QUINDIO",
            "ENELAR": "ARAUCA",
            "EMCALI": "CALI",
            "EMCARTAGO": "CARTAGO",
            "EPM-EADE": "ANTIOQUIA",
            "ENERCA": "CASANARE",
            "CODENSA-EEC": "BOGOTA",
            "CARIBESOL": "CARIBE SOL",
            "CARIBEMAR": "CARIBE MAR",
            "CHEC": "CALDAS",
            "CEDENAR": "NARIÑO",
            "CEDELCA": "CAUCA",
            "CENS": "NORTE DE SANTANDER",
            "CETSA": "TULUA",
            "ESSA": "SANTANDER",
            "ELECTROCAQUETA": "CAQUETA",
            "ELECTROHUILA": "HUILA",
            "ELECTROMETA": "META",
            "ENERTOLIMA": "TOLIMA",
            "EBSA": "BOYACA",
            "EEP": "PEREIRA",
            "BAJO PUTUMAYO": "BAJO PUTUMAYO"
        },
        "tension_mapping": {
            "1 OR": "1 OR",
            "1 COMP": "1 COMP",
            "1 US": "1 US",
            "2": "2",
            "3": "3",
            "4": "4"
        }
    },
    "QI": {
        "name": "QI",
        "instrucciones_file": "config/instrucciones/qi.txt",
        "mercado_mapping": {
            "ARAUCA": "ARAUCA",
            "ANTIOQUIA": "ANTIOQUIA",
            "ATLÁNTICO, GUAJIRA Y MAGDALENA": "CARIBE SOL",
            "CESAR, SUCRE, CORDOBA Y BOLIVAR": "CARIBE MAR",
            "BOYACA": "BOYACA",
            "CALI, YUMBO Y PUERTO TEJADA": "CALI",
            "CALDAS": "CALDAS",
            "CAQUETA": "CAQUETA",
            "CASANARE": "CASANARE",
            "CAUCA": "CAUCA",
            "CARTAGO": "CARTAGO",
            "CHOCO": "CHOCO",
            "CORDOBA": "CORDOBA",
            "BOGOTÁ y CUNDINAMARCA": "BOGOTA",
            "BOYACA": "BOYACA", 
            "HUILA": "HUILA",
            "LA GUAJIRA": "LA GUAJIRA",
            "MAGDALENA": "MAGDALENA",
            "META": "META",
            "NARIÑO": "NARIÑO",
            "NORTE DE SANTANDER": "NORTE SANTANDER",
            "QUINDIO": "QUINDIO",
            "PEREIRA": "RISARALDA",
            "RUITOQUE": "RUITOQUE",
            "SANTANDER": "SANTANDER",
            "TOLIMA": "TOLIMA",
            "TULUÁ": "TULUA",
            "VALLE DEL CAUCA": "VALLE"
        },
        "tension_mapping": {
            "1 POR": "1 OR",
            "1 COM": "1 COMP",
            "1 PC": "1 US",
            "2": "2",
            "3": "3"
        }
    },
    "NEU": {
        "name": "Neu",
        "instrucciones_file": "config/instrucciones/neu.txt",
        "mercado_mapping": {
            "ANTIOQUIA": "ANTIOQUIA",
            "ATLANTICO": "ATLANTICO",
            "BOLIVAR": "BOLIVAR",
            "BOYACA": "BOYACA",
            "CALDAS": "CALDAS",
            "CALI": "CALI",
            "CAQUETA": "CAQUETA",
            "CAUCA": "CAUCA",
            "CESAR": "CESAR",
            "CHOCO": "CHOCO",
            "CORDOBA": "CORDOBA",
            "CUNDINAMARCA": "CUNDINAMARCA",
            "HUILA": "HUILA",
            "LA GUAJIRA": "LA GUAJIRA",
            "MAGDALENA": "MAGDALENA",
            "META": "META",
            "NARIÑO": "NARIÑO",
            "NORTE DE SANTANDER": "NORTE DE SANTANDER",
            "QUINDIO": "QUINDIO",
            "PEREIRA": "PEREIRA",
            "SANTANDER": "SANTANDER",
            "TOLIMA": "TOLIMA",
            "VALLE": "VALLE",
            "CARTAGO": "CARTAGO"
        },
        "tension_mapping": {
            "1 OR": "1 OR",
            "1 COMP": "1 COMP",
            "1 US": "1 US",
            "2": "2",
            "3": "3",
            "4": "4"
        }
    }
} 